org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# android.useAndroidX=true
# android.enableJetifier=true
# org.gradle.jvmargs=-Xmx1536M
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
# Namespace properties for ML Kit modules
google_mlkit_commons.android.namespace=com.google.mlkit.common